# -------------------hicoin-web-app Deployment ------------------- #
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: hicoin-web-app
  name: hicoin-web-app
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: test-app
  template:
    metadata:
      labels:
        k8s-app: test-app
    spec:
      containers:
      - name: test-app
        image: 192.168.31.240:5000/test-app:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          nfs:
            server: 192.168.31.240
            path: "/data/test-app"
