# ------------------- hicoin-web-app Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: test-app
  name: test-app
  namespace: default
spec:  
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 10000
  selector:
    k8s-app: test-app