# ------------------- hicoin-web-api Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: hicoin-web-api
  name: hicoin-web-api
  namespace: default
spec:  
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    k8s-app: hicoin-web-api
