# -------------------hicoin-web-app Deployment ------------------- #
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: test-hicoin-io
  name: test-hicoin-io
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: test-hicoin-io
  template:
    metadata:
      labels:
        k8s-app: test-hicoin-io
    spec:
      containers:
      - name: test-hicoin-io
        image: ${REGISTRY_API}/test-app:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
          - name: data-${ENV}
            mountPath: /data
      volumes:
      - name: data-nfs
        nfs:         
          server: 192.168.31.240
          path: /exports
      - name: data-aws
        awsElasticBlockStore:
          volumeID: vol-0b6d8df71329a4ba7
          fsType: ext4
        