# -------------------hicoin-web-app Deployment ------------------- #
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: test-hicoin-io
  name: test-hicoin-io
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: test-hicoin-io
  template:
    metadata:
      labels:
        k8s-app: test-hicoin-io
    spec:
      containers:
      - name: test-hicoin-io
        image: ${REGISTRY_API}/test-app:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
    ${N}nfs:         
    ${N}  server: 192.168.31.240
    ${N}  path: /exports
    ${E}ebs:         
    ${E}  server: 192.168.31.240
    ${E}  path: /exports


